### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by stefanheijnen** [iot6466/CO2-Sensors#1]
Hi,

I tried to compile your plugin with the latest version of ESPEasy and I get this error:

```
/home/stefan/Documents/PlatformIO/Projects/ESPEasy/src/_P178_MICSVZ89TE.ino: In function 'boolean Plugin_178(byte, EventStruct*, String&)':
/home/stefan/Documents/PlatformIO/Projects/ESPEasy/src/_P178_MICSVZ89TE.ino:32:37: error: 'SENSOR_TYPE_DUAL' was not declared in this scope
         Device[deviceCount].VType = SENSOR_TYPE_DUAL;
                                     ^
```

**Comment by iot6466** [comment]
Hi Stefan,

could be, I compiled it with the ESPEasy-mega-20200310 version. I'll have a
look and keep you informed.

**Comment by stefanheijnen** [comment]
I fixed it by changing line 32 to:

`Device[deviceCount].VType = Sensor_VType::SENSOR_TYPE_DUAL;`
